### ISSUE TITLE
animation not working in listview

### ISSUE THREAD

**Issue by fukemy** [IhorKlimov/FlutterProgressButton#1]
Hello, thank for great library.
i putted reveal button in listview but animation does not running when click. plz help

**Comment by fukemy** [comment]
i will upload video soon

**Comment by IhorKlimov** [comment]
At this point you basically want me to contribute to your app. Feel free to use the code, but anything else, especially not related to the sample - is your problem

**Comment by fukemy** [comment]
my question is 'the animation not working when put button in listview', it's not related to my app or my code. the video it only show the result when i running.
